### ISSUE TITLE
gotify-compose.yml

### ISSUE THREAD

**Issue by drifter75** [drifter75/special-eureka#3]
```yaml
version: '3.8'
networks:
  postgres15-network:
    external: true
  swarm-internal:
    external: true
  traefik-network:
    external: true
#
services:
  gotify:
    image: gotify/server:2.6.1
    environment:
      - TZ='Europe/Berlin'
      - GOTIFY_DATABASE_DIALECT=postgres
      - GOTIFY_DATABASE_CONNECTION="host=postgres15 port=5432 user=gotify dbname=gotify password='XXXXXXXXXXXXXXXXX' sslmode=disable"
    networks:
      - swarm-internal
      - postgres15-network
      - traefik-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == kimsufi1
      update_config:
        delay: 15s
        parallelism: 1
        monitor: 10s
        failure_action: rollback
        max_failure_ratio: 0.55
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gotify.service=gotify"
        - "traefik.http.routers.gotify.rule=Host(`gotify.example.com`)"
        - "traefik.http.routers.gotify.entrypoints=websecure"
        - "traefik.http.services.gotify.loadbalancer.server.port=80"
        - "traefik.http.routers.gotify.tls=true"
        - "traefik.http.routers.gotify.tls.certresolver=letsencrypt"
        - "traefik.http.services.gotify.loadbalancer.passhostheader=true"


```
